### ISSUE TITLE
mormot.core.json,  GetJsonField doesn't handle jtArrayStart case

### ISSUE THREAD

**Issue by wxinix** [synopse/mORMot2#33] opened 2021-05-16 15:26 UTC
mormot.core.json,  line 2650

function GetJsonField, case JSON_TOKENS[P^] does NOT handle jtArrayStart case.

This makes JSONToObject fail to parse a variant array field like this:  [8, 12, 14, 20]

**Comment by synopse** [comment] 2021-05-17 08:59
By design, GetJsonField() does not support JSON objects or arrays.
It only parses simple values.

I don't understand what is your use case of JsonToObject.
Could you please show a class definition which has problem be parsed?

**Comment by wxinix** [comment] 2021-05-17 09:58
Hi ab,

the class is defined as below (mORMot 1.18 is working fine):  Speed_Thresholds_Mph is a variant,  taking values of a TDoubleDynArray, such as [8, 12, 16, 20].

First I call ObjectToJSON to get a JSONStr, which worked just fine generating the correct JSONStr.  Then the generated JSONStr   cannot be loaded by JSONToObject.  I think internally it breaks at GetJsonField.  

Note: mORMOt 1.18 both ObjectToJSON and JSONToObject worked for this case.

  TZpi = class(TTimeSeriesOrm)
  strict private
    FTolling_Zone_ID: Integer;
    FSpeed_Thresholds_Mph: Variant;
  published
    property Tolling_Zone_ID: Integer read FTolling_Zone_ID write FTolling_Zone_ID;
    property Speed_Thresholds_Mph: Variant read FSpeed_Thresholds_Mph write FSpeed_Thresholds_Mph;
  end;

**Comment by synopse** [comment] 2021-05-17 14:30
Did you specify jpoHandleCustomVariants in the ObjectToJson() function?

**Comment by wxinix** [comment] 2021-05-17 14:53
> Did you specify jpoHandleCustomVariants in the ObjectToJson() function?

Thanks for the heads up.

Now I specified `[jpoHandleCustomVariants]` in `JSONToObject`,  and it seems working now. 

Question :  ObjectToJson is defined in `mormot.core.json` and `mormot.core.text`, which one should I use?

**Comment by synopse** [comment] 2021-05-17 15:31
You are right: ObjectToJson() should be in a single unit.
Fixed by https://github.com/synopse/mORMot2/commit/63f778aa7248b661ece4c9ec92a6621170a10fbd

Please note that you should better not have posted an issue here, but create a new discussion thread on our forum.

**Closed by synopse** 2021-05-17 15:31 UTC
