### ISSUE TITLE
Not all tests passed

### ISSUE THREAD

**Issue by lbcsy** [synopse/mORMot2#252] opened 2024-05-01 09:56 UTC
Start to look into mORMot 2, run tests first and got 4 failures:
  - Dmi smbios: 45 assertions passed  1.82ms
!  - SID: 1 / 794 FAILED  7.41ms
  - Quick select: 4,015 assertions passed  187.13ms
  - TSynCache: 408 assertions passed  1.12ms
  - TSynFilter: 1,005 assertions passed  7.92ms
  - TSynValidate: 677 assertions passed  2.37ms
  - TSynLogFile: 62 assertions passed  814us
  - TSynUniqueIdentifier: 1,300,004 assertions passed  549.14ms
     200000 ComputeNew in 7.01ms i.e. 27.2M/s, aver. 35ns
  Total failed: 1 / 20,487,289  - Core base FAILED  7.22s
...
     1000 URI parametrized execute in 977us i.e. 0.9M/s, aver. 977ns
!  - DNS and LDAP: 3 / 1,069 FAILED  981.90ms
     time.google.com : 2024-05-01 09:48:49.965Z = 2024-05-01 09:48:50.359Z
  - RTSP over HTTP: 2,100 assertions passed  294.72ms
  - RTSP over HTTP buffered write: 2,100 assertions passed  281.98ms
  - TTunnelLocal: 9,120 assertions passed  195.46ms
  - IP addresses: 53 assertions passed  1.56ms
  - THttpPeerCache: 14,013 assertions passed  231.56ms
     2000 messages in 2ms i.e. 0.9M/s, aver. 1us, 182.7 MB/s
     10000 altered in 725us i.e. 13.1M/s, aver. 72ns, 2.4 GB/s
  Total failed: 3 / 37,700  - Network protocols FAILED  2.01s

**Comment by synopse** [comment] 2024-05-01 10:09
Which compiler do you use?
Which version of the source code and statics are you using?
On which operating system are you running it?
On which computer are your running it?
Do you have access to an unrestricted/unproxied Internet connection?

The automated tests are currently passing:
https://luti.tranquil.it/history/tis-test-mormot2
So I guess this is due to some specificity on your system.

Please use the forum for such discussion.
Closing this issue here because it is not reproducible.

**Closed by synopse** 2024-05-01 10:09 UTC

**Comment by lbcsy** [comment] 2024-05-01 11:11
It seems the SID tests do not cover the case where user is created and linked to Azure Acitve Directory, i.e., my user's SID starts with 'S-1-12-1-', thus below checking in the test failed:
`CurrentRawSid(s1, wttProcess);
  CurrentRawSid(s2, wttThread);
  Check(SidCompare(pointer(s1), pointer(s2)) = 0);
  s := RawSidToText(s1);
  CheckUtf8(IdemPChar(pointer(s), 'S-1-5-'), s);
  // domain users are S-1-5-21-*, but LOCAL_SYSTEM is S-1-5-18`
